[workspace]
channels = ["conda-forge", "bioconda"]
name = "Assembleur"
platforms = ["linux-64"]
version = "0.1.0"

[tasks._preparedir]
cmd = "rm -rf build"

[tasks._configure]
cmd = "cmake -S $INIT_CWD -B $INIT_CWD/build"
description = "Configure the C++ project using CMake"
inputs = ["$INIT_CWD/CMakeLists.txt"]
outputs = ["$INIT_CWD/build/Makefile"]

[tasks._configure_static]
cmd = "cmake -S $INIT_CWD -B $INIT_CWD/build -DCMAKE_EXE_LINKER_FLAGS='-static'"
description = "Configure the C++ project using CMake"
inputs = ["$INIT_CWD/src/*", "$INIT_CWD/CMakeLists.txt"]
outputs = ["$INIT_CWD/build"]

[tasks.build]
cmd = "cmake --build $INIT_CWD/build"
description = "Build the C++ project using CMake"
depends-on = ["_configure"]
inputs = ["$INIT_CWD/src/*", "$INIT_CWD/CMakeLists.txt"]
outputs = ["$INIT_CWD/build/ramilass"]

[tasks.test]
cmd = "$INIT_CWD/build/run_tests"
description = "Run the test suite"
inputs = ["$INIT_CWD/build/ramilass"]

[tasks.start]
args = [
    { "arg" = "file", "default" = "data/reads.fasta" },
    { "arg" = "output", "default" = "reads" },
]
cmd = "$INIT_CWD/build/ramilass $INIT_CWD/{{ file }} $INIT_CWD/output -o {{ output }} --fuse --gfa --debug --max-contig-len 11000 --popping-passes 0"
description = "Run the app"
inputs = ["$INIT_CWD/build/ramilass"]
outputs = ["$INIT_CWD/output/{{ output }}.gfa", "$INIT_CWD/output/{{ output }}.fasta"]

[tasks.ramilass]
cmd = "$INIT_CWD/build/ramilass"
description = "Run the app"
inputs = ["$INIT_CWD/build"]

[tasks.tofasta]
args = [
    { "arg" = "input", "default" = "$INIT_CWD/data/reads.fastq.fq" },
    { "arg" = "output", "default" = "$INIT_CWD/data/reads.fasta" }]
cmd = "sed ':a;N;$!ba;s/+\\n/+/g' {{ input }} | grep -v \"^+\" | sed \"s/@/>/g\" > {{ output }}"
inputs = ["{{ input }}"]
outputs = ["{{ output }}"]

[tasks._build_debug]
cmd = "rm -fr $INIT_CWD/build && cmake -B $INIT_CWD/build -DCMAKE_BUILD_TYPE=Debug && cmake --build $INIT_CWD/build"
depends-on = ["_preparedir"]

[feature.memcheck.tasks.check_memory]
cmd = "valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --track-origins=yes $INIT_CWD/build/ramilass $INIT_CWD/data/reads.fasta --fuse"
depends-on = ["_build_debug"]
description = "Check memory leaks using Valgrind"

[dependencies]
cmake = ">=4.1.2,<5"
gtest = ">=1.17.0,<2"
cxx-compiler = ">=1.11.0,<2"
make = ">=4.4.1,<5"

[feature.quast.dependencies]
quast = { version = ">=5.3.0,<6", channel = "bioconda" }

[feature.bench.dependencies]
minia = { version = ">=3.2.6,<4", channel = "bioconda" }
spades = { version = ">=4.2.0,<5", channel = "bioconda" }

[feature.memcheck.dependencies]
valgrind = ">=3.25.1,<4"

[feature.plot.dependencies]
python = ">=3.8,<3.13"

[feature.plot.pypi-dependencies]
seaborn = "*"
pandas = "*"
matplotlib = "*"

[feature.plot.tasks.plotit]
cmd = "cd benchmark && python -s plot.py"
description = "Generate plots from benchmark results"
inputs = ["benchmark/plot.py", "benchmark/*.csv"]
outputs = ["benchmark/*.png"]

[environments]
plot = { features = ["plot"], no-default-feature = true }
memcheck = { features = ["memcheck"], no-default-feature = true }
bench = { features = ["bench", "quast"], no-default-feature = true }
